// src/content/posts/cooking-blog/Counter.vue
<script setup>
import { ref } from "vue";

const value = ref(0);

const increment = () => {
  value.value += 1;
};

const decrement = () => {
  value.value -= 1;
};
</script>

<template>
  <div>
    <h4 class="!mb-0">Simple counter that works!</h4>
    <div class="flex items-center gap-2">
      <button class="btn btn-primary btn-sm" @click="decrement">-</button>
      <p>{{ value }}</p>
      <button class="btn btn-primary btn-sm" @click="increment">+</button>
    </div>
  </div>
</template>

// src/components/solid/Counter.tsx
import { createMemo, createSignal } from "solid-js";

export const Counter = ({}) => {
  const [get, write] = createSignal(0);

  const memo = createMemo(() => get() + 1);

  return (
    <div class="flex items-center gap-2 ">
      <button onClick={() => write((v) => v + 1)}>Increment</button>
      <p>Count: {get()}</p>
      <button onClick={() => write((v) => v - 1)}>Decrement</button>

      <div>+1: {memo()}</div>
    </div>
  );
};
