// src/content/posts/cooking-blog/Counter.tsx
import { type FC, type ReactNode, useState } from "react";

interface Props {
  children?: ReactNode;
}

export const Counter: FC<Props> = ({}) => {
  const [value, setValue] = useState(0);

  return (
    <div>
      <h4 className="!mb-0">Simple counter that works!</h4>
      <div className="flex items-center gap-2">
        <button className="btn btn-primary btn-sm" onClick={() => setValue((v) => v - 1)}>
          -
        </button>
        <p>{value}</p>
        <button className="btn btn-primary btn-sm" onClick={() => setValue((v) => v + 1)}>
          +
        </button>
      </div>
    </div>
  );
};

// src/content/posts/cooking-blog/Counter.vue
<script setup lang="ts">
import { ref } from "vue";

const value = ref(0);
</script>

<template>
  <div>
    <h4 class="!mb-0">Simple counter that works!</h4>
    <div class="flex items-center gap-2">
      <button class="btn btn-sm btn-primary" @click="value--">-</button>
      <p>{{ value }}</p>
      <button class="btn btn-sm btn-primary" @click="value++">+</button>
    </div>
  </div>
</template>
